fixtures/fixtureapp/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about', TemplateView.as_view(template_name='fixtureapp/about.html'), name='about'),
    path('team/<slug:team_id_slug>/', views.TeamView.as_view(), name='team_by_id'),
    path('wag/', views.WAGView.as_view(), name='teamWAG')
]

fixtures/fixtures/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('fixtureapp.urls'))
]

fixtures/fixtureapp/models.py
from django.db import models


class Team(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Match(models.Model):
    VENUES = (
        ('T', 'Abbeydale Top Pitch'),
        ('B', 'Abbeydale Bottom Pitch'),
        ('D', 'Dronfield Woodhouse'),
        ('A', 'Away')
    )
    date = models.DateField()
    time = models.TimeField()
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    opposition = models.CharField(max_length=30)
    venue = models.CharField(max_length=1, choices=VENUES)
    notes = models.CharField(max_length=100, default="", blank=True)

    def __str__(self):
        return f"{self.date}: {self.team} v {self.opposition}"

fixtures/fixtureapp/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import Q
from .models import Match, Team
import datetime


class HomeView(generic.ListView):
    template_name = 'fixtureapp/home.html'
    context_object_name = 'fixtures'

    def get_queryset(self):
        """return matches except away games, order by date, next 10 only"""
        s_start = datetime.date(2021, 4, 17)
        today = datetime.date.today()
        if s_start > today:
            start = s_start
        else:
            start = today
        end = start + datetime.timedelta(days=15)
        # return Match.objects.exclude(venue='A').filter(date__range=(start, end)).order_by('date')
        return Match.objects.exclude(venue='A').order_by('date')


class TeamView(generic.ListView):
    queryset = Match.objects.all().order_by('date')
    template_name = 'fixtureapp/team.html'
    context_object_name = 'fixtures'

    def get_queryset(self):
        """return all team_id team matches"""
        return Match.objects.filter(team_id=self.kwargs.get('team_id_slug')).order_by('date')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        m = Match(team_id=self.kwargs.get('team_id_slug'))
        data['team_name'] = m.team
        return data

class WAGView(generic.ListView):
    queryset = Match.objects.all().order_by('date')
    template_name = 'fixtureapp/home.html'
    context_object_name = 'fixtures'

    def get_queryset(self):
        """return all team_id team matches"""
        return Match.objects.filter(Q(team_id=9)|Q(team_id=8)|Q(team_id=14)).order_by('date')

fixtures/fixtureapp/templates/fixtureapp/about.html
{% extends 'fixtureapp/base.html' %}

{% block content %}
{% load static %}
<div id="about">
    <div style="float: left; width: 70%;">
        <p>This website was created by Martin Slater using the Django Python Framework. The database utilises sqlite.</p>
        <p>For more information contact me at martinhslater@gmail.com</p>
    </div>
    <div style="float: left; width: 30%;">
        <a id="git" href="https://github.com/Slats99"><img src="{% static 'images/GitHub.png' %}"width="75" height="75"></a>
    </div>
</div>
{% endblock %}

fixtures/fixtureapp/templates/fixtureapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fixtures</title>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'fixtureapp/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="{% static 'images/favicon.ico' %}" rel="icon" type="image/x-icon" />
</head>
<body>
    <div class="topnav" id="myTopnav">
        <a href="{% url 'home' %}" class="active">Home</a>
        <div class="dropdown">
            <button class="dropbtn">Teams
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="{% url 'team_by_id' '1' %}">1st Team</a>
                <a href="{% url 'team_by_id' '2' %}">2nd Team</a>
                <a href="{% url 'team_by_id' '5' %}">3rd Team</a>
                <a href="{% url 'team_by_id' '3' %}">4th Team</a>
                <a href="{% url 'team_by_id' '6' %}">5th Team</a>
                <a href="{% url 'team_by_id' '4' %}">Sunday Team</a>
                <a href="{% url 'teamWAG' %}">W&G</a>
            </div>
        </div>
        <a href="{% url 'admin:index' %}">Admin</a>
        <a href="{% url 'about' %}">About</a>
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
        </a>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

fixtures/fixtureapp/templates/fixtureapp/home.html
{% extends 'fixtureapp/base.html' %}

{% block content %}
    <h3>Upcoming Home Fixtures</h3>
    {% if fixtures %}
        {% regroup fixtures by date as date_list %}
        {% for date in date_list %}
        <div id="date_div">{{ date.grouper|date:'l jS F' }}
            {% for fixture in date.list %}
            <div id="fixture_div">{{ fixture.time|time:'G:i' }}   {{ fixture.team }}
                v  {{ fixture.opposition }}, {{ fixture.get_venue_display }}</div>
            {% endfor %}
        </div>
        {% endfor %}
    {% else %}
        <p>No fixtures are available.</p>
    {% endif %}
{% endblock %}

fixtures/fixtureapp/templates/fixtureapp/team.html
{% extends 'fixtureapp/base.html' %}

{% block content %}
    <h3>{{ team_name }} Team Fixtures</h3>
    {% if fixtures %}
    <table style="width:100%">
        <tr>
        <th>Date</th>
        <th>Start Time</th>
        <th>Opposition</th>
        <th>Venue</th>
        </tr>
        {% for fixture in fixtures %}
            <tr>
                <td>{{ fixture.date|date:'F jS' }} </td>
                <td>{{ fixture.time|time:'G:i' }}</td>
                <td>{{ fixture.opposition }}</td>
                <td>{{ fixture.get_venue_display }}</td>
            </tr>
        {% endfor %}
    {% else %}
        <p>No fixtures are available.</p>
    {% endif %}
{% endblock %}